In [1]:
import numpy as np

In [2]:
array_estados = np.ones((4,4))
array_estados 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [3]:
array_estado_total = np.arange(1, 37)
array_estado_total

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [4]:
array_estado1 = np.zeros((9))
array_estado1 

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
array_estado2 = np.zeros((9))
array_estado2 

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
array_estado3 = np.zeros((9))
array_estado3 

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
array_estado4 = np.zeros((9))
array_estado4 

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
array_estado_pares = np.arange(2, 37, 2)
array_estado_pares

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36])

In [12]:
array_estado_impares = np.arange(1, 37, 2)
array_estado_impares

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35])